# Generated by Django 3.2.9 on 2021-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
